---
- name: Update apt cache (if older than 1h)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages + base_extra_packages }}"
    state: present
