---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable periodic security upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Configure unattended-upgrades policy
  ansible.builtin.template:
    src: 52unattended-upgrades-local.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    mode: "0644"
