---
- name: Add Cloudflare package signing key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: "0644"

- name: Add cloudflared apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg]
      https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release }} main
    filename: cloudflared
    state: present

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: latest
    update_cache: true
    cache_valid_time: 3600
  notify: Restart cloudflared
